services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - ./apps/web/.env.local
    volumes:
      - .:/app
    command: pnpm --filter web run dev     # <--- این خط را اضافه کن

    ports:
      - "${WEB_PORT:-6500}:6500"
#    depends_on:
#      - api
    restart: unless-stopped
    networks:
      - default




  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: django_app
    env_file:
      - ./apps/api/.env
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app


    networks:
      - default

  postgres:
    image: postgres:16-alpine
    container_name: flowhq_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: flowhq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - flowhq_postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7-alpine
    container_name: flowhq_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - flowhq_redis_data:/data
    networks:
      - default

volumes:
  flowhq_postgres_data:
  flowhq_redis_data:

networks:
  default:
    driver: bridge


