version: "3.8"

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-6500}:6500"
    environment:
      - APP_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - default

  cms:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    ports:
      - "${CMS_PORT:-7000}:7000"
    environment:
      - APP_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - default
      
  api:
    build:
      context: ./apps/api 
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings

    networks:
      - default

networks:
  coolify:
    external: true
    name: coolify
