# Generated by Django 4.2.17 on 2025-12-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0002_remove_conversation_service_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='service_account',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='phone_number_id',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='service_type',
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='chat_manage_created_9759e7_idx'),
        ),
        migrations.CreateModel(
            name='GmailAccounts',
            fields=[
                ('serviceaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat_manager.serviceaccount')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.CharField(max_length=500)),
                ('watch_expiration', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Gmail Account',
            },
            bases=('chat_manager.serviceaccount',),
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('serviceaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat_manager.serviceaccount')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_id', models.CharField(max_length=40, unique=True)),
                ('access_token', models.TextField()),
                ('business_account_id', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'WhatsApp Account',
            },
            bases=('chat_manager.serviceaccount',),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat_manager.message')),
                ('wa_message_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('location', 'Location'), ('contact', 'Contact'), ('template', 'Template')], default='text', max_length=20)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=200, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('template_language', models.CharField(blank=True, default='fa', max_length=10, null=True)),
                ('template_parameters', models.JSONField(blank=True, default=list)),
                ('wa_status', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat_manager.whatsappaccount')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
            },
            bases=('chat_manager.message',),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat_manager.message')),
                ('subject', models.CharField()),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_email', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('gmail_message_id', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=500, null=True)),
                ('html_body', models.TextField(blank=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('service_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='chat_manager.gmailaccounts')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
            },
            bases=('chat_manager.message',),
        ),
    ]
