# Generated by Django 4.2.17 on 2025-12-21 06:09
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0003_alter_message_options_remove_message_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Email Message', 'verbose_name_plural': 'Email Messages'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='gmail_message_id',
            new_name='email_message_id',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='gmail_thread_id',
            new_name='email_thread_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='chat_manager.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='chat_manager.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(blank=True, choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=10),
        ),
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
    ]
