# Generated by Django 4.2.17 on 2025-12-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0004_alter_emailmessage_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='conversation',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_manager.conversation'),
        ),
    ]
