# Generated by Django 4.2.17 on 2025-12-22 13:44

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from chat_manager.models import EmailMessage as RealEmailMessage
from chat_manager.models import WhatsAppMessage as RealWhatsAppMessage
from chat_manager.models import Message as RealMessage


def set_polymorphic_ctype(apps, schema_editor):
    """
    تنظیم polymorphic_ctype_id برای رکوردهای موجود
    """
    # گرفتن مدل‌ها از طریق apps (نه import مستقیم!)
    Message = apps.get_model('chat_manager', 'Message')
    EmailMessage = apps.get_model('chat_manager', 'EmailMessage')
    WhatsAppMessage = apps.get_model('chat_manager', 'WhatsAppMessage')

    # گرفتن ContentType ها
    # ⚠️ نکته: باید از مدل واقعی استفاده کنیم، نه apps.get_model

    email_ct = ContentType.objects.get_for_model(RealEmailMessage)
    whatsapp_ct = ContentType.objects.get_for_model(RealWhatsAppMessage)
    message_ct = ContentType.objects.get_for_model(RealMessage)

    # آپدیت EmailMessage ها
    email_count = EmailMessage.objects.filter(
        polymorphic_ctype_id__isnull=True
    ).update(polymorphic_ctype_id=email_ct.id)

    print(f"✅ {email_count} EmailMessage آپدیت شد")

    # آپدیت WhatsAppMessage ها
    whatsapp_count = WhatsAppMessage.objects.filter(
        polymorphic_ctype_id__isnull=True
    ).update(polymorphic_ctype_id=whatsapp_ct.id)

    print(f"✅ {whatsapp_count} WhatsAppMessage آپدیت شد")

    # آپدیت Message های معمولی (اگر دارید)
    message_count = Message.objects.filter(
        polymorphic_ctype_id__isnull=True
    ).update(polymorphic_ctype_id=message_ct.id)

    print(f"✅ {message_count} Message آپدیت شد")


def reverse_set_polymorphic_ctype(apps, schema_editor):
    """
    در صورت rollback، polymorphic_ctype_id را null می‌کنیم
    """
    Message = apps.get_model('chat_manager', 'Message')
    Message.objects.all().update(polymorphic_ctype_id=None)




class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0006_message_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.RunPython(
            set_polymorphic_ctype,
            reverse_code=reverse_set_polymorphic_ctype
        ),
    ]
