# Generated by Django 4.2.17 on 2025-12-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chat_manager', '0007_fix_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceaccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
