# Generated by Django 4.2.17 on 2025-12-22 14:00

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def set_serviceaccount_polymorphic_ctype(apps, schema_editor):
    """
    تنظیم polymorphic_ctype_id برای ServiceAccount های موجود
    """
    ServiceAccount = apps.get_model('chat_manager', 'ServiceAccount')
    WhatsAppAccount = apps.get_model('chat_manager', 'WhatsAppAccount')
    GmailAccounts = apps.get_model('chat_manager', 'GmailAccounts')
    ContentTypeModel = apps.get_model('contenttypes', 'ContentType')

    # پیدا کردن یا ایجاد ContentType ها
    try:
        whatsapp_ct = ContentTypeModel.objects.get(
            app_label='chat_manager',
            model='whatsappaccount'
        )
    except ContentTypeModel.DoesNotExist:
        print("⚠️ ContentType برای WhatsAppAccount یافت نشد، در حال ایجاد...")
        whatsapp_ct = ContentTypeModel.objects.create(
            app_label='chat_manager',
            model='whatsappaccount'
        )

    try:
        gmail_ct = ContentTypeModel.objects.get(
            app_label='chat_manager',
            model='gmailaccounts'
        )
    except ContentTypeModel.DoesNotExist:
        print("⚠️ ContentType برای GmailAccounts یافت نشد، در حال ایجاد...")
        gmail_ct = ContentTypeModel.objects.create(
            app_label='chat_manager',
            model='gmailaccounts'
        )

    try:
        service_ct = ContentTypeModel.objects.get(
            app_label='chat_manager',
            model='serviceaccount'
        )
    except ContentTypeModel.DoesNotExist:
        print("⚠️ ContentType برای ServiceAccount یافت نشد، در حال ایجاد...")
        service_ct = ContentTypeModel.objects.create(
            app_label='chat_manager',
            model='serviceaccount'
        )

    # آپدیت WhatsAppAccount ها
    whatsapp_count = WhatsAppAccount.objects.filter(
        polymorphic_ctype_id__isnull=True
    ).update(polymorphic_ctype_id=whatsapp_ct.id)

    if whatsapp_count > 0:
        print(f"✅ {whatsapp_count} WhatsAppAccount آپدیت شد")

    # آپدیت GmailAccounts ها
    gmail_count = GmailAccounts.objects.filter(
        polymorphic_ctype_id__isnull=True
    ).update(polymorphic_ctype_id=gmail_ct.id)

    if gmail_count > 0:
        print(f"✅ {gmail_count} GmailAccounts آپدیت شد")

    # آپدیت ServiceAccount های معمولی (اگر دارید)
    service_count = ServiceAccount.objects.filter(
        polymorphic_ctype_id__isnull=True
    ).update(polymorphic_ctype_id=service_ct.id)

    if service_count > 0:
        print(f"✅ {service_count} ServiceAccount آپدیت شد")

    print("🎉 تنظیم polymorphic_ctype_id برای ServiceAccount ها با موفقیت انجام شد!")


def reverse_serviceaccount_polymorphic_ctype(apps, schema_editor):
    """
    در صورت rollback
    """
    ServiceAccount = apps.get_model('chat_manager', 'ServiceAccount')
    ServiceAccount.objects.all().update(polymorphic_ctype_id=None)
    print("⏪ polymorphic_ctype_id برای ServiceAccount ها به null برگشت")

class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0008_alter_serviceaccount_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            set_serviceaccount_polymorphic_ctype,
            reverse_code=reverse_serviceaccount_polymorphic_ctype
        ),
    ]
