# Generated by Django 4.2.17 on 2025-12-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0009_fix_serviceaccount_polymorphic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='channelidentity',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='chat_manager.organization'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat_manager.contact'),
        ),
    ]
