# Generated by Django 4.2.17 on 2025-12-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0010_remove_conversation_contact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat_manager.channelidentity'),
        ),
    ]
