# Generated by Django 4.2.17 on 2025-12-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0011_alter_conversation_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='contact_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
