# Generated by Django 4.2.17 on 2026-01-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0012_conversation_contact_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='message_type',
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('location', 'Location'), ('contact', 'Contact'), ('template', 'Template')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='default', max_length=150),
        ),
    ]
