# Generated by Django 4.2.17 on 2026-01-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0013_remove_whatsappmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='service_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
    ]
