# Generated by Django 4.2.17 on 2026-01-31 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0014_serviceaccount_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('serviceaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat_manager.serviceaccount')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('gmail_api', 'Gmail API'), ('outlook', 'Outlook/Office 365'), ('yahoo', 'Yahoo Mail'), ('custom', 'Custom SMTP/IMAP')], default='gmail', max_length=20)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_encription', models.CharField(choices=[('tls', 'TLS (STARTTLS)'), ('ssl', 'SSL/TLS'), ('none', 'None')], default='ssl', max_length=10)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.IntegerField(default=933)),
                ('imap_encription', models.CharField(choices=[('tls', 'TLS (STARTTLS)'), ('ssl', 'SSL/TLS'), ('none', 'None')], default='tls', max_length=10)),
                ('app_password', models.TextField(blank=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_uri', models.CharField(blank=True, max_length=500)),
                ('watch_expiration', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_folder', models.CharField(default='INBOX', max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('chat_manager.serviceaccount',),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='service_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='chat_manager.emailaccount'),
        ),
    ]
