# Generated by Django 4.2.17 on 2026-02-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0015_emailaccount_alter_emailmessage_service_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='instance_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='instance_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='instance_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='jid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatsappaccount',
            name='push_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_from_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='quoted_message_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='smtp_encription',
            field=models.CharField(choices=[('tls', 'TLS (STARTTLS)'), ('ssl', 'SSL/TLS'), ('none', 'None')], default='tls', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='phone_number_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
