# Generated by Django 4.2.17 on 2026-02-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0016_whatsappaccount_connected_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelidentity',
            unique_together={('channel', 'external_id')},
        ),
        migrations.RemoveField(
            model_name='channelidentity',
            name='service_account',
        ),
    ]
