# Generated by Django 4.2.17 on 2026-02-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0017_alter_channelidentity_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='chat_manager.contact'),
        ),
    ]
