# Generated by Django 4.2.17 on 2026-02-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0019_add_message_composite_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], default='text', max_length=20, null=True),
        ),
    ]
